### ISSUE TITLE
Using the "EMF model" wizard crashes Eclipse

### ISSUE THREAD

**Issue by agarciadom** [epsilonlabs/emf-cbp#8]
For an initial experiment involving the EMF Compare UI, I registered extension parsers for CBP (.cbpbin, .cbptext) and then tried using the "EMF Model" wizard to create and populate a simple resource with the Exeed editor.

However, it seems that crashes Eclipse completely with little warning. One thing that does happen right before it crashes, however, is this exception:

```
java.io.FileNotFoundException: /resource/patchTest/example.cbptext (No such file or directory)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(FileOutputStream.java:270)
at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
at org.eclipse.epsilon.cbp.io.CBPTextSerialiser.serialise(CBPTextSerialiser.java:69)
at org.eclipse.epsilon.cbp.resource.CBPTextResourceImpl.save(CBPTextResourceImpl.java:34)
at org.eclipse.epsilon.emc.emf.EmfModel.store(EmfModel.java:660)
at org.eclipse.epsilon.emf.dt.NewEmfModelWizard.doFinish(NewEmfModelWizard.java:146)
at org.eclipse.epsilon.emf.dt.NewEmfModelWizard.access$0(NewEmfModelWizard.java:118)
at org.eclipse.epsilon.emf.dt.NewEmfModelWizard$1.run(NewEmfModelWizard.java:92)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

**Comment by agarciadom** [comment]
This was due to interpreting URIs always as file:// paths, instead of delegating on EMF's CommonPlugin pluggable way of decoding URIs. It would result in an exception, which would then be "handled" by invoking `System.exit(0)` (!). The URI problem was fixed in b93099d, and the System.exit calls were removed in 9c251e2. Closing this issue.
