### ISSUE TITLE
Better handling of REMOVE_MANY notifications

### ISSUE THREAD

**Issue by agarciadom** [epsilonlabs/emf-cbp#9]
While disposing the model created from the "EMF Model" wizard (particularly, while doing `getErrors().clear()`, we get an IndexOutOfBoundsException:

```
java.lang.IndexOutOfBoundsException: Index: 0
at java.util.Collections$EmptyList.get(Collections.java:4454)
at org.eclipse.epsilon.cbp.event.EventAdapter.notifyChanged(EventAdapter.java:228)
at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
```

The offending code seems to be related to handling the REMOVE_MANY notification, which assumes that the list of old values has always exactly one element:

```java
@SuppressWarnings("unchecked")
List<Object> list = (List<Object>) n.getOldValue();
if (list.get(0) instanceof EObject) {
```

This is not the case, however. The javadoc for REMOVE_MANY says it clearly:

```java
  /**
  * An {@link Notification#getEventType event type} indicating that 
  * a several values have been removed from a list-based feature of the notifier.
  * @see Notification#getEventType
  */
 int REMOVE_MANY = 6;
```

In fact, if we look at the uses of REMOVE_MANY, clearing an empty list will result in a REMOVE_MANY notification with an empty list as the old value. EMF CBP needs to handle this notification in a more robust way.

**Comment by agarciadom** [comment]
I would suggest adding these three unit tests to CBP's suite:

* Clear an empty EList
* Clear an EList with 1 element
* Clear an EList with 2+ elems

This has to be done with the `.clear()` method, and ideally with the `.remove(...)` methods as well.

**Comment by agarciadom** [comment]
This seems to have been fixed now.
